### ISSUE TITLE
Development libraries.

### ISSUE THREAD

**Issue by ghost** [17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod/dropzone_js#2]
I would like to discuss a bit the libraries used for testing and development, starting by the ones marked by [this line](https://github.com/17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod/node-dropzone/commit/8f57e30bf780b7a51530c99711182e10efb30df5#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R49).

**Comment by ghost** [comment]
# cb-http-client, httpify, proxyquire

Are we gonna use blockchain explorers after all? 
I thought we will query the network directly (using WebRTC in the browser)?

**Comment by 17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod** [comment]
I think the path to pursue here is to abstract the persistence layer by way of the connection object. In doing so, the users can choose what backend they prefer. I very much like the route that you've been pursuing with spv-mode, but I would like to preserve the option for users to query a blockchain explorer as well. We can remove those dependencies for now though if they're in your way.

**Comment by 17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod** [comment]
@aynik - Is it your expectation that a client can spool up via a web browser, and connect to a public bitcoind server, or would you expect that the bitcoind server is running on the site that is hosting the static pages?

**Comment by ghost** [comment]
I think browsers that support WebRTC can use the network as it is to pull data (I guess SPV is a bit more trustworthy than block explorers) but when is not available the best would be to use existing explorers, instead of providing a btcd server side which cannot be scrutinized and isn't even open to custom usage (like explorers are).
