### ISSUE TITLE
21, Inc. - Distributed Mining & Marketplaces

### ISSUE THREAD

**Issue by eragmus** [17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod/dropzone_js#4]
Does 21's recently announced plan mesh with DropZone's mission (of a market protocol layered directly on top of the Bitcoin protocol)?

Info:
- https://21.co
- https://21.co/faq
- https://medium.com/@21dotco/the-21-bitcoin-computer-1d28d652b57b
- http://blogs.wsj.com/moneybeat/2015/09/21/21-inc-releases-first-product-a-bitcoin-computer/
- https://www.reddit.com/r/Bitcoin/comments/3lucwl/21co_website_has_just_been_updated_introducing/

If you notice, there's a clear trend where 21 is trying to incentivize a market for micro-transactions. I'm not sure what they're using, but it seems DropZone could help fit their niche.

**Comment by krisives** [comment]
What advantage would I have to spending $400 to buy that instead of buying a $20 stick?

**Comment by ghost** [comment]
I think dropzone is in direct competition with 21's permitted (in contrast to permission-less) distributed marketplace. Dropzone is just a protocol which can be implemented by any device, you can even build your own "bitcoin computer" using an [orange pi](http://www.orangepi.org/) and an [antminer u3](https://bitmaintech.com/productDetail.htm?pid=00020150109104550452NTD3NdYY0669) for a nice price and employ the mined satoshis with dropzone. The missing part here is the microtransaction network, which I assume 21 is managing themselves, perhaps opening a duplex payment channel with every 21's hardware wallet.

**Comment by eragmus** [comment]
How do you know 21's market will be permissioned? In fact, for the reasons you stated, this is why I think dropzone might fit in perfectly as one piece of the software that helps make 21's vision come true. Could they theoretically use it?

**Comment by ghost** [comment]
I don't know for sure but I just cannot imagine how they will profit if their hardware can be easily replicated ([component breakdown](http://samuelrpatterson.com/breakdown-of-hardware-costs-for-new-21-inc-bitcoin-computer/)) and they release their server/client software (currently nothing was released on their github). Perhaps permissioned is not the right term, I guess it will be relatively easy to use their services but they should (for their own survival) keep certain key elements of the system under control. Only in the (just guessing) improbable event in which they enable anybody to create assets on the blockchain which are compatible with their services then I could see a dropzone integration.

**Comment by krisives** [comment]
All marketing aside this machine doesn't introduce anything I think changes this project. People can already mine insignificant amounts of BTC with their GPUs and buy and sell things with it. Nobody needs to buy a very poor quality $400 ASIC being marketed as a "bitcoin computer" - If size is a problem use a $20 stick computer. If you're hellbent on having an ASIC that mines almost nothing buy a USB miner.

**Comment by eragmus** [comment]
Balaji commented that most of the software, whatever possible, will be open sourced. Further, he has said that their long term roadmap is "most assuredly anti-centralization" (presumably WRT mining) and offered to speak with Peter Todd (obviously a stringent advocate for decentralization and core Bitcoin principles). Also, have you seen the screenshot of their CLI?

> https://i.imgur.com/0Cyvyxj.jpg

Last but not least, Balaji commented on Reddit with many more details, including acceptance to do an AMA:

> https://www.reddit.com/r/Bitcoin/comments/3lv6zj/ama_request_ceo_of_21inc_balaji_srinivasan/cv9zq9q

WRT 'profit', I admit I'm not sure how the above benevolent plans fit in. Currently, they operate a mining pool, so it's possible they intend that to be their profit center. They had originally planned to take 75% of mining rewards from all embedded mining chips, and that may still be true. Whatever they decide though, I have faith it will adhere to Bitcoin ethos and promote a harmonious end result.

P.S. Balaji gave a very famous "voice vs. exit" talk, which may add color to his worldview:

> https://www.reddit.com/r/Bitcoin/comments/2yrrh9

**Comment by ghost** [comment]
Yeah, I'm following closely the developments of 21 Inc, but still I think is too early and most of the discussion is based on pure speculation. This said, I don't think they are contributing to decentralization that much; as you noted they operate a mining pool, sell you mining hardware which you cannot configure (switch pool) and a bitcoin wallet whose keys aren't under your control. As far as I can see, they cannot "open up" any of these parts. So what's left to open source? The microtransations server and the command line tool, I'm excited to see how similar are those to lightning and dropzone.
