### ISSUE TITLE
Any objection to changing the file structure...

### ISSUE THREAD

**Issue by 17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod** [17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod/dropzone_js#7]
I'd like to rename the src folders 'lib' and rename the test folder to 'spec' to more closely match the bitcore codebase. Also, is 'examples' needed anymore? Could/Should we implement a test class for BlockchainSpv instead?

**Comment by ghost** [comment]
ACK, let's rename both.

Examples is outdated (we can rm it for now), in the future I'd like to add some, in order to have them for README.md as well.
