### ISSUE TITLE
Message encryption

### ISSUE THREAD

**Issue by ghost** [17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod/dropzone_js#8]
We can discuss here wether we should continue using diffie-hellman or a public key protocol like [ECIES](https://github.com/bitpay/bitcore-ecies).

I'm a supporter of ECIES, therefore I think private keys should be the only source of identity in dropzone.

Please expose any cases where this is not desired.

**Comment by loon3** [comment]
Have you done any experimenting with the ECIES library?  I'm having some issues using it in the browser via Bower.
