### ISSUE TITLE
Feedback on the WP

### ISSUE THREAD

**Issue by unsystemizer** [17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod/dropzone_js#9]
### URL Identifiers are Centralized

Depending on what's being sold, it may not necessarily be a weakness. It could also be a benefit.
- Could a seller create a free alphanumeric (or non-free) Counterparty asset for goods he frequently sells, e.g.: https://coindaddy.io/search?network=xcp&q=contraband, and then issue DZITCRTE with `d="DEX#CONTRABAND"` that would indicate that product details can be found in enhanced asset info?
  This could keep transaction sizes smaller and save transaction fees in the medium run without compromising in terms of information. Since the assets are rather persistent, groups of sellers that voluntarily adhere to common standards could advertise the same asset. 
  Sellers can also better guard their privacy by using standardized product and service classification rather than posting their own.
  It could be confusing if the actual asset (token) was on sale rather than the good, which is why free alphanumeric assets could be more suitable for information dissemination.
- Buyers and sellers can benefit from easier access to standardized information from the Counterparty asset database. In some cases this additional "standardization" could facilitate new types of trades (price arbitrage across different locations) and business arrangements (for example one might price his product in any Counterparty token, or even another asset (`COFFEE\BACON`).)
### Bad sellers

Perhaps sellers could be encouraged to use Proof of Burn.
### API Sources
- One possible sources, OpenStreetMap.org, is available over Tor https://help.openstreetmap.org/questions/45919/use-josm-and-tor
- If asset information was published as enhanced Counterparty asset information, it would probably be less obvious which asset is being queried.

**Comment by 17Q4MX2hmktmpuUKHFuoRmS5MfB5XPbhod** [comment]
Though certainly this is a possibility for users, I believe that introducing that level of coupling between Drop Zone clients, and the Counterparty system, would likely increase the size of the drop zone codebase (and runtime) considerably. (Plus it would introduce the need to query a Counterparty server) 

I appreciate this suggestion, but believe there are probably much better uses for our efforts at this (early) time in our development.

**Comment by unsystemizer** [comment]
I agree, just wanted to put this up there for future consideration.
